version: '3.7'

services:
  client:
    image: 'kurtis/client:2.0.0-SNAPSHOT'
    ports:
      - 8080:8081
    environment:
      - GRPC_ADDRESS=server
      - GRPC_PORT=6565

  server:
    image: 'kurtis/server:2.0.0-SNAPSHOT'
    environment:
      - GRPC_PORT=6565